version: '3.4'

services:
  restarone_redis:
    image: redis:4.0-alpine
    command: redis-server
    volumes:
      - shared_data:/var/shared/redis
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SECRET_KEY_BASE
        - DATABASE_URL
    depends_on:
      - postgres
    volumes:
      - .:/app      
    ports:
      - 3000:3000
    links: 
      - postgres
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://username:password@ipaddresshostname:5432/database_name
      SECRET_KEY_BASE: xxxxxxxxxxxx
      RAILS_LOG_TO_STDOUT: 1
      RAILS_SERVE_STATIC_FILES: 1
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && rails server -b 0.0.0.0"
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "20"

  postgres:
    image: postgres:12.1
    restart: always
    environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - 5099:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none

volumes:
   db_data:
   attachments:
   shared_data:
